### ISSUE TITLE
python snippet

### ISSUE THREAD

**Issue by qubolino** [MkLHX/Raspberry_Pi_Master_for_ESP32_I2C_SLAVE#4] opened 2021-08-13 14:49 UTC
i am trying to use the `ESP32_I2C_Slave/examples/slave_sender/slave_sender.ino` example with python on my raspi.

it detects the device well:
```
i2cdetect -y 1|grep 04
00:          -- 04 -- -- -- -- -- -- -- -- -- -- --
```

however my python (3.7.3) snippet doesn't return anything relevant
```
import smbus
import time
bus = smbus.SMBus(1)
address = 0x04

# [start = 0x02][length = 0x04][crc = 0x61][end = 0x04]
bus.write_byte(address, 0x02)
bus.write_byte(address, 0x04)
bus.write_byte(address, 0x61)
bus.write_byte(address, 0x04)

print(bus.read_byte(address))
```

could you kindly help me with this (or better, provide a working snippet?)

**Comment by MkLHX** [comment] 2021-08-13 14:58
Hello @qubolino 
This library works only with the v2.x.x of the c++ esp32 side library.
I forgot to put this information on the readme/doc.

Since v3.x.x the i2c handshake changed and I haven't the time to put my lib iso of these changes.

**Comment by MkLHX** [comment] 2021-08-13 15:00
More here
https://github.com/gutierrezps/ESP32_I2C_Slave/issues/12

**Comment by qubolino** [comment] 2021-08-13 15:00
cool. i’m happy to downgrade... do you know how i can do this?

**Comment by MkLHX** [comment] 2021-08-13 15:02
Use this
https://github.com/gutierrezps/ESP32_I2C_Slave/releases/tag/v0.2.0

**Comment by qubolino** [comment] 2021-08-13 15:04
excellent. and do i have to use MkLHX lib or just anything? (my snippet essentially)

**Comment by MkLHX** [comment] 2021-08-13 15:06
You do what you want. If you have the time to re write crc8 and pack and unpack classes you can use your own lib.

I2c slave on esp32 side need data encoding and this lib help devs to make it easy.

**Comment by qubolino** [comment] 2021-08-13 15:07
cheers. will try and keep you posted

**Comment by qubolino** [comment] 2021-08-13 20:22
so i rebuilt for esp32 with v0.2.0 (and also v0.1.0) while using your `read_from_rpi_to_esp32()` function.
unfortunately it doesn't work well for me. i constantly get `128`...

**Comment by qubolino** [comment] 2021-08-21 07:15
> Since v3.x.x the i2c handshake changed and I haven't the time to put my lib iso of these changes.

how big of an effort would this be? i might as well do it. would you be able to help?

**Comment by MkLHX** [comment] 2021-08-21 07:51
Hello,

The effort is about testing and be sure there is no regression in our use case.

If you have the devices and the time to submit a PR it will be appreciate.

**Comment by MkLHX** [comment] 2021-09-09 08:26
Any update here?
as i said here https://github.com/MkLHX/Raspberry_Pi_Master_for_ESP32_I2C_SLAVE/issues/2#issuecomment-831383722
and as we used in production using v0.2 of the c++ lib side allow this python lib to work.

For now i haven't the time to change any thing in this repo because that not just a simple lib for everybody we use it in production and any changes have to be tested before release.

**Comment by qubolino** [comment] 2021-09-09 19:46
hi. like i mentioned  https://github.com/MkLHX/Raspberry_Pi_Master_for_ESP32_I2C_SLAVE/issues/4#issuecomment-898701744 i was unable to get it working.

i threw the towel for now and am using arduino nano which solves my problem but not the issue. i'm happy to close it though. thanks again.

**Comment by MkLHX** [comment] 2021-09-10 07:24
ok i close the issue.

**Closed as completed by MkLHX** 2021-09-10 07:24 UTC
